[versions]

java = "25"
spring-boot = "3.5.7"

#-----------------------------------------------------------------------------------------------------------------------

[libraries]

lombok = { module = "org.projectlombok:lombok" }

#-----------------------------------------------------------------------------------------------------------------------

[plugins]

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

#-----------------------------------------------------------------------------------------------------------------------

[bundles]
